services:
  db:
    ports:
      - "5432:5432" # expose PostgreSQL for testing
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    volumes:
      - ./server:/app/server
      - node_modules:/app/server/node_modules
      - .:/workspace
      - node_modules:/workspace/node_modules
    environment:
      SERVER_DROP_DATABASE_ON_STARTUP: "true" # drop the database on startup
      SERVER_SEED_DATABASE_ON_STARTUP: "true" # seed the database on startup
      SERVER_DATABASE_ECHO: "false" # enable database echo
      VITE_HOT_RELOAD: "true" # enable hot reload
      VITE_DEV_MODE: "true" # enable dev mode
      VITE_API_BASE_URL: "http://localhost:8000"
    ports:
      - "5173:5173" # expose Vite dev server

volumes:
  db_data:
  node_modules:


networks:
  mynetwork:
