version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydatabase
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork
    volumes:
      - .:/app/server

volumes:
  db_data:

networks:
  mynetwork:
