services:
  db:
    ports:
      - "5432:5432" # expose PostgreSQL for testing
      - "5173:5173" # expose Vite dev server
  app:
    build:
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    volumes:
      - ./server:/app/server
    environment:
      DATABASE_DROP: "true" # drop the database on startup
      VITE_HOT_RELOAD: "true" # enable hot reload
      VITE_DEV_MODE: "true" # enable dev mode

volumes:
  db_data:

networks:
  mynetwork:
