/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as AuthUsersIndexImport } from './routes/_auth/users/index'
import { Route as AuthNamespacesIndexImport } from './routes/_auth/namespaces/index'
import { Route as AuthUsersUserIdImport } from './routes/_auth/users/$userId'
import { Route as AuthNamespacesNamespaceIdIndexImport } from './routes/_auth/namespaces/$namespaceId/index'
import { Route as AuthNamespacesNamespaceIdRunsIndexImport } from './routes/_auth/namespaces/$namespaceId/runs/index'
import { Route as AuthNamespacesNamespaceIdDatasetsIndexImport } from './routes/_auth/namespaces/$namespaceId/datasets/index'
import { Route as AuthNamespacesNamespaceIdRunsRunIdImport } from './routes/_auth/namespaces/$namespaceId/runs/$runId'
import { Route as AuthNamespacesNamespaceIdDatasetsDatasetIdImport } from './routes/_auth/namespaces/$namespaceId/datasets/$datasetId'

// Create/Update Routes

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthUsersIndexRoute = AuthUsersIndexImport.update({
  id: '/_auth/users/',
  path: '/users/',
  getParentRoute: () => rootRoute,
} as any)

const AuthNamespacesIndexRoute = AuthNamespacesIndexImport.update({
  id: '/_auth/namespaces/',
  path: '/namespaces/',
  getParentRoute: () => rootRoute,
} as any)

const AuthUsersUserIdRoute = AuthUsersUserIdImport.update({
  id: '/_auth/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRoute,
} as any)

const AuthNamespacesNamespaceIdIndexRoute =
  AuthNamespacesNamespaceIdIndexImport.update({
    id: '/_auth/namespaces/$namespaceId/',
    path: '/namespaces/$namespaceId/',
    getParentRoute: () => rootRoute,
  } as any)

const AuthNamespacesNamespaceIdRunsIndexRoute =
  AuthNamespacesNamespaceIdRunsIndexImport.update({
    id: '/_auth/namespaces/$namespaceId/runs/',
    path: '/namespaces/$namespaceId/runs/',
    getParentRoute: () => rootRoute,
  } as any)

const AuthNamespacesNamespaceIdDatasetsIndexRoute =
  AuthNamespacesNamespaceIdDatasetsIndexImport.update({
    id: '/_auth/namespaces/$namespaceId/datasets/',
    path: '/namespaces/$namespaceId/datasets/',
    getParentRoute: () => rootRoute,
  } as any)

const AuthNamespacesNamespaceIdRunsRunIdRoute =
  AuthNamespacesNamespaceIdRunsRunIdImport.update({
    id: '/_auth/namespaces/$namespaceId/runs/$runId',
    path: '/namespaces/$namespaceId/runs/$runId',
    getParentRoute: () => rootRoute,
  } as any)

const AuthNamespacesNamespaceIdDatasetsDatasetIdRoute =
  AuthNamespacesNamespaceIdDatasetsDatasetIdImport.update({
    id: '/_auth/namespaces/$namespaceId/datasets/$datasetId',
    path: '/namespaces/$namespaceId/datasets/$datasetId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth/users/$userId': {
      id: '/_auth/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthUsersUserIdImport
      parentRoute: typeof rootRoute
    }
    '/_auth/namespaces/': {
      id: '/_auth/namespaces/'
      path: '/namespaces'
      fullPath: '/namespaces'
      preLoaderRoute: typeof AuthNamespacesIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth/namespaces/$namespaceId/': {
      id: '/_auth/namespaces/$namespaceId/'
      path: '/namespaces/$namespaceId'
      fullPath: '/namespaces/$namespaceId'
      preLoaderRoute: typeof AuthNamespacesNamespaceIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth/namespaces/$namespaceId/datasets/$datasetId': {
      id: '/_auth/namespaces/$namespaceId/datasets/$datasetId'
      path: '/namespaces/$namespaceId/datasets/$datasetId'
      fullPath: '/namespaces/$namespaceId/datasets/$datasetId'
      preLoaderRoute: typeof AuthNamespacesNamespaceIdDatasetsDatasetIdImport
      parentRoute: typeof rootRoute
    }
    '/_auth/namespaces/$namespaceId/runs/$runId': {
      id: '/_auth/namespaces/$namespaceId/runs/$runId'
      path: '/namespaces/$namespaceId/runs/$runId'
      fullPath: '/namespaces/$namespaceId/runs/$runId'
      preLoaderRoute: typeof AuthNamespacesNamespaceIdRunsRunIdImport
      parentRoute: typeof rootRoute
    }
    '/_auth/namespaces/$namespaceId/datasets/': {
      id: '/_auth/namespaces/$namespaceId/datasets/'
      path: '/namespaces/$namespaceId/datasets'
      fullPath: '/namespaces/$namespaceId/datasets'
      preLoaderRoute: typeof AuthNamespacesNamespaceIdDatasetsIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth/namespaces/$namespaceId/runs/': {
      id: '/_auth/namespaces/$namespaceId/runs/'
      path: '/namespaces/$namespaceId/runs'
      fullPath: '/namespaces/$namespaceId/runs'
      preLoaderRoute: typeof AuthNamespacesNamespaceIdRunsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/users/$userId': typeof AuthUsersUserIdRoute
  '/namespaces': typeof AuthNamespacesIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/namespaces/$namespaceId': typeof AuthNamespacesNamespaceIdIndexRoute
  '/namespaces/$namespaceId/datasets/$datasetId': typeof AuthNamespacesNamespaceIdDatasetsDatasetIdRoute
  '/namespaces/$namespaceId/runs/$runId': typeof AuthNamespacesNamespaceIdRunsRunIdRoute
  '/namespaces/$namespaceId/datasets': typeof AuthNamespacesNamespaceIdDatasetsIndexRoute
  '/namespaces/$namespaceId/runs': typeof AuthNamespacesNamespaceIdRunsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/users/$userId': typeof AuthUsersUserIdRoute
  '/namespaces': typeof AuthNamespacesIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/namespaces/$namespaceId': typeof AuthNamespacesNamespaceIdIndexRoute
  '/namespaces/$namespaceId/datasets/$datasetId': typeof AuthNamespacesNamespaceIdDatasetsDatasetIdRoute
  '/namespaces/$namespaceId/runs/$runId': typeof AuthNamespacesNamespaceIdRunsRunIdRoute
  '/namespaces/$namespaceId/datasets': typeof AuthNamespacesNamespaceIdDatasetsIndexRoute
  '/namespaces/$namespaceId/runs': typeof AuthNamespacesNamespaceIdRunsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_auth/users/$userId': typeof AuthUsersUserIdRoute
  '/_auth/namespaces/': typeof AuthNamespacesIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/namespaces/$namespaceId/': typeof AuthNamespacesNamespaceIdIndexRoute
  '/_auth/namespaces/$namespaceId/datasets/$datasetId': typeof AuthNamespacesNamespaceIdDatasetsDatasetIdRoute
  '/_auth/namespaces/$namespaceId/runs/$runId': typeof AuthNamespacesNamespaceIdRunsRunIdRoute
  '/_auth/namespaces/$namespaceId/datasets/': typeof AuthNamespacesNamespaceIdDatasetsIndexRoute
  '/_auth/namespaces/$namespaceId/runs/': typeof AuthNamespacesNamespaceIdRunsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/users/$userId'
    | '/namespaces'
    | '/users'
    | '/namespaces/$namespaceId'
    | '/namespaces/$namespaceId/datasets/$datasetId'
    | '/namespaces/$namespaceId/runs/$runId'
    | '/namespaces/$namespaceId/datasets'
    | '/namespaces/$namespaceId/runs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/users/$userId'
    | '/namespaces'
    | '/users'
    | '/namespaces/$namespaceId'
    | '/namespaces/$namespaceId/datasets/$datasetId'
    | '/namespaces/$namespaceId/runs/$runId'
    | '/namespaces/$namespaceId/datasets'
    | '/namespaces/$namespaceId/runs'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/logout'
    | '/_auth/users/$userId'
    | '/_auth/namespaces/'
    | '/_auth/users/'
    | '/_auth/namespaces/$namespaceId/'
    | '/_auth/namespaces/$namespaceId/datasets/$datasetId'
    | '/_auth/namespaces/$namespaceId/runs/$runId'
    | '/_auth/namespaces/$namespaceId/datasets/'
    | '/_auth/namespaces/$namespaceId/runs/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  AuthUsersUserIdRoute: typeof AuthUsersUserIdRoute
  AuthNamespacesIndexRoute: typeof AuthNamespacesIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
  AuthNamespacesNamespaceIdIndexRoute: typeof AuthNamespacesNamespaceIdIndexRoute
  AuthNamespacesNamespaceIdDatasetsDatasetIdRoute: typeof AuthNamespacesNamespaceIdDatasetsDatasetIdRoute
  AuthNamespacesNamespaceIdRunsRunIdRoute: typeof AuthNamespacesNamespaceIdRunsRunIdRoute
  AuthNamespacesNamespaceIdDatasetsIndexRoute: typeof AuthNamespacesNamespaceIdDatasetsIndexRoute
  AuthNamespacesNamespaceIdRunsIndexRoute: typeof AuthNamespacesNamespaceIdRunsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  AuthUsersUserIdRoute: AuthUsersUserIdRoute,
  AuthNamespacesIndexRoute: AuthNamespacesIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
  AuthNamespacesNamespaceIdIndexRoute: AuthNamespacesNamespaceIdIndexRoute,
  AuthNamespacesNamespaceIdDatasetsDatasetIdRoute:
    AuthNamespacesNamespaceIdDatasetsDatasetIdRoute,
  AuthNamespacesNamespaceIdRunsRunIdRoute:
    AuthNamespacesNamespaceIdRunsRunIdRoute,
  AuthNamespacesNamespaceIdDatasetsIndexRoute:
    AuthNamespacesNamespaceIdDatasetsIndexRoute,
  AuthNamespacesNamespaceIdRunsIndexRoute:
    AuthNamespacesNamespaceIdRunsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/logout",
        "/_auth/users/$userId",
        "/_auth/namespaces/",
        "/_auth/users/",
        "/_auth/namespaces/$namespaceId/",
        "/_auth/namespaces/$namespaceId/datasets/$datasetId",
        "/_auth/namespaces/$namespaceId/runs/$runId",
        "/_auth/namespaces/$namespaceId/datasets/",
        "/_auth/namespaces/$namespaceId/runs/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/_auth/users/$userId": {
      "filePath": "_auth/users/$userId.tsx"
    },
    "/_auth/namespaces/": {
      "filePath": "_auth/namespaces/index.tsx"
    },
    "/_auth/users/": {
      "filePath": "_auth/users/index.tsx"
    },
    "/_auth/namespaces/$namespaceId/": {
      "filePath": "_auth/namespaces/$namespaceId/index.tsx"
    },
    "/_auth/namespaces/$namespaceId/datasets/$datasetId": {
      "filePath": "_auth/namespaces/$namespaceId/datasets/$datasetId.tsx"
    },
    "/_auth/namespaces/$namespaceId/runs/$runId": {
      "filePath": "_auth/namespaces/$namespaceId/runs/$runId.tsx"
    },
    "/_auth/namespaces/$namespaceId/datasets/": {
      "filePath": "_auth/namespaces/$namespaceId/datasets/index.tsx"
    },
    "/_auth/namespaces/$namespaceId/runs/": {
      "filePath": "_auth/namespaces/$namespaceId/runs/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
