[project]
name = "server"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Miroslav Hrabal", email = "mhn@email.cz"},
]
dependencies = ["litestar[attrs,brotli,pydantic,sqlalchemy,standard]>=2.14.0", "psycopg[binary,pool]>=3.2.5"]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

# [build-system]
# requires = ["pdm-backend"]
# build-backend = "pdm.backend"

[tool.pdm]
distribution = true
